name: movie_series_app
description: Movie list application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  go_router_paths: ^0.2.2
  google_fonts: ^8.0.1
  hooks_riverpod: ^3.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.0+1
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  generate: true

  shaders:
    - shaders/simple_shader.frag
  assets:
    - assets/images/
